### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by lasmacdonald** [ds4owd-001/md-02-assignments-lasmacdonald#1]
@larnsce @mianzg @sskorik01

**Comment by larnsce** [comment]
Thank you for working through the assignment @lasmacdonald. Could you double-check that you did the commit to track your changes and then also push to GitHub?

It’s Steps 2 & 3 as described on the website and also in the assignments itself: https://ds4owd-001.github.io/website/assignments/md-03/am-03-1-data-transformation.html#step-2-commit-and-push-your-changes

**Comment by lasmacdonald** [comment]
Thanks, @larnsce. Yes, I followed those steps. I've attached a screenshot showing the commit. Because these changes were already committed, it doesn't appear I can do so again.
![Screenshot 2023-11-15 at 9 02 18 AM](https://github.com/ds4owd-001/md-02-assignments-lasmacdonald/assets/148254210/606b823b-3d78-41cb-8024-aa6ad220ae0f)

**Comment by larnsce** [comment]
Yes, that looks good, @lasmacdonald. What happens when you now also click the "Push" button and then enter your GitHub username and GitHub PAT as a password. In your screenshot, you only have the "pull" button in the top-right corner, but if you switched to "Changes" view in the top-left corner of that window, you would get a "Push" button (screenshot 1). Otherwise also from the main RStudio window on the Git pane in the top-right window (screenshot 2).

**Screenshot 1**

![Screenshot 2023-11-16 at 09 26 56](https://github.com/ds4owd-001/md-02-assignments-lasmacdonald/assets/18212549/e40c5e7d-3fa2-4fde-9569-981bce9718cc)

**Screenshot 2**

![Screenshot 2023-11-16 at 09 27 02](https://github.com/ds4owd-001/md-02-assignments-lasmacdonald/assets/18212549/215e07ef-3bc3-43e4-a119-cc3fa8b951da)

**Comment by lasmacdonald** [comment]
Ohhh, apologies! I missed that critical push step. I believe it's complete, now. Thanks for your patience and support. 
<img width="1102" alt="Screenshot 2023-11-16 at 6 12 17 PM" src="https://github.com/ds4owd-001/md-02-assignments-lasmacdonald/assets/148254210/913e48d6-ec34-4596-a987-527061f12e9f">

**Comment by larnsce** [comment]
Thank you for seeing it through, @lasmacdonald. You can see a comparison of what was deleted/edited (red - left side) and was added (green - right side) here: https://github.com/ds4owd-001/md-02-assignments-lasmacdonald/commit/99e13d4748ebebada3e09c1c9b7b5dc2c6b089ca

I have added some comments. On each line, one can add comments. A bit like you would do in MS Word with comments and track changes.

I will close the issue for you now.
